name: epidemic_forecast
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21.3
  - pandas=1.5.3
  - requests=2.28.2
  - scikit-learn=1.2.2
  - pip
  - pip:
      - tensorflow==2.13.0
      - python-telegram-bot==13.15
      - python-dotenv==1.0.0
